### PR TITLE
CI: Update Ubuntu container tags

### PR DESCRIPTION
**Pull request by TSC21**

### CODE REVIEW

**Comment by TSC21** [comment]
@lamping7 https://travis-ci.org/PX4/sitl_gazebo/jobs/487241327#L487

**Comment by lamping7** [comment]
Crap. I think that came from here: https://github.com/PX4/containers/commit/64154790cc53ea598d6222d28abf36358487cc4a#diff-8fe21b75f1d50e84b43f3c2125b20d20

Basically Travis is specifying a UID that isn't in the container, so the entrypoint is trying to match the UID, but it doesn't create the user before modifying it's UID to match.

Travis command is: `docker run -it ... --env=LOCAL_USER_ID="$(id -u)" ...`

**Comment by TSC21** [comment]
> Crap. I think that came from here: PX4/containers@6415479#diff-8fe21b75f1d50e84b43f3c2125b20d20

Yeah I found about that, that's why I am applying 13eb34b, hoping it can solve it.

**Update:** yes it works as a workaround.

**Comment by TSC21** [comment]
> so the entrypoint is trying to match the UID, but it doesn't create the user before modifying it's UID to match.

@lamping7 should that be fixed on the container then? I am ok for now taking the UID from it, but could be useful on other cases. Shouldn't be limited in that sense.

**Comment by lamping7** [comment]
> should that be fixed on the container then?

Yeah. I think so. @dagar?

**Comment by dagar** [comment]
Last week I changed it to create a default user and have the optional environment variable modify the UID of the existing user. https://github.com/PX4/containers/commit/64154790cc53ea598d6222d28abf36358487cc4a

**Comment by TSC21** [comment]
> Last week I changed it to create a default user and have the optional environment variable modify the UID of the existing user. PX4/containers@6415479

But somehow it seems that it tries to find an UID `user`, which doesn't exist in the container. So something in the logic doesn't seem right.

**Comment by TSC21** [comment]
@dagar @lamping7 I am going to merge this as is and then we can think of a solution on how to set the UID correctly (since it seems like it's not doing the correct thing).

**Pull request merged**
