### PR TITLE
added int64 message

### PR DESCRIPTION
**Pull request by addy1997**

### CODE REVIEW

**Comment by Jaeyoung-Lim** [comment]
@addy1997 This PR is simply adding a message, where it is not being used.

Could you shine more details on why this can be useful? thanks

**Comment by addy1997** [comment]
@Jaeyoung-Lim, sure. So, while using **int32** and **int64**, I tried computing their processing time (as given below)
Please note: the calculations are based on running this SITL on mac OS

```
**int64: 66 ms
int32: 140 ms**

```
Some metrics
`Compilation time: 0.42 sec, absolute running time: 0.34 sec, cpu time: 0.27 sec, memory peak: 96 Mb, absolute service time: 0,78 sec` 

Coming to the point, when a parameter assumes a value that is outside the range of `int32`, it overflows and increases program execution time. Whereas. using `int 64` is beneficial in such a situation.

**Comment by Jaeyoung-Lim** [comment]
@addy1997 Since it is not being used in any of the plugins, I don't think your use case is publicly accessible from this repository.

Therefore I will not be able to merge this unless there is some plugin that is consuming the message

**Comment by addy1997** [comment]
> @addy1997 Since it is not being used in any of the plugins, I don't think your use case is publicly accessible from this repository.
> 
> Therefore I will not be able to merge this unless there is some plugin that is consuming the message

okay.

**Pull request closed without merging**
